# It would be good to not need this
# https://github.com/ndmitchell/weeder/issues/24

- package:
  - name: dejafu
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends: semigroups
- package:
  - name: dejafu-tests
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends: transformers
