#!/usr/bin/env bash

source .travis/setup.sh

# do not echo hackage password!
set +x

# sometimes uploading the package will "fail" in that an error is reported,
# but it actually worked.  this commonly seems to happen with timeouts.  in
# these cases, retrying the deploy job will fail, because the package has
# actually been uploaded.  it's not a great solution, but ignore failures here
# and just manually check that the deploy worked...
set +e

for pkg in concurrency dejafu hunit-dejafu tasty-dejafu; do
  echo "$stack upload $pkg"
  echo -e "barrucadu\n${HACKAGE_PASSWORD}\nn" | $stack upload $pkg
done

true
