#!/usr/bin/env bash

source .travis/setup.sh

# do not echo hackage password!
set +e

for pkg in concurrency dejafu hunit-dejafu tasty-dejafu; do
  echo "$stack upload $pkg"
  echo "barrucadu\n${HACKAGE_PASSWORD}\nn" | $stack upload $pkg
done
