#!/usr/bin/env bash

source .travis/setup.sh

$stack install stylish-haskell

$stack build

curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh  | sh -s .

$stack exec ./style.sh
git diff --exit-code
