[book]
title = "Déjà Fu"
authors = ["Michael Walker (barrucadu)"]
description = "Systematic concurrency testing meets Haskell."
language = "en"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/barrucadu/dejafu"
cname = "dejafu.docs.barrucadu.dev"
